# Generated by Django 4.2.7 on 2024-05-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(default='Нет отзывов'),
        ),
    ]
